---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
data:
  config.properties: |
    #single node install config
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    #query.max-total-memory-per-node=500MB
    query.max-memory=1GB
    query.max-memory-per-node=500MB
  jvm.config: |
    -server
    -Xmx1G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+UseGCOverheadLimit
    -XX:+ExitOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=256M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |
    io.trino=DEBUG
  node.properties: |
    node.environment=docker
    node.data-dir=/data/trino
    node.id=159570f5-a17c-4f6e-bf42-f93256e49815
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-config
data:
  aerospike.properties: |
    connector.name=aerospike
    aerospike.hostlist=asdb-dev.aerospike.svc.cluster.local
    aerospike.split-number=4
    aerospike.strict-schemas=false
    aerospike.record-key-hidden=false
    aerospike.enable-statistics=false
    aerospike.insert-require-key=false
    aerospike.table-desc-dir=/etc/trino/aerospike
    aerospike.clientpolicy.tls.enabled=false
    aerospike.clientpolicy.user=colton
    aerospike.clientpolicy.password=admin123
    aerospike.record-key-name=__key
---
apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  type: NodePort
  selector:
    app: trino
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-aerospike-connector
  labels:
    app: trino
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino
        image: coltonmarkle/trino-aerospike:4.4.1  # Replace with the name of your Docker image
        ports:
        - containerPort: 8080  # Adjust if using a different port
        volumeMounts:
        - name: trino-config
          mountPath: /etc/trino
        - name: trino-catalog-config
          mountPath: /etc/trino/catalog
        # Add other configurations like environment variables, resource limits, etc.
      volumes:
      - name: trino-config
        configMap:
          name: trino-config
      - name: trino-catalog-config
        configMap:
          name: trino-catalog-config  # You should create a ConfigMap with your Trino configuration
---
